// Public types remain at LibClient.Components.Input.DayOfTheWeek.* for all existing callers.
// The Mode union and the days list live in the namespace module so gallery autogenerated renders
// (which reference LibClient.Components.Input.DayOfTheWeek.MaybeOne etc.) continue to compile.
namespace LibClient.Components.Input

open LibClient

module DayOfTheWeek =

    type Mode =
    | MaybeOne of Value: Option<DayOfTheWeek> * OnChange: (Option<DayOfTheWeek> -> unit)
    | One      of Value: Option<DayOfTheWeek> * OnChange: (DayOfTheWeek         -> unit)
    | Set      of Value: Set<DayOfTheWeek>    * OnChange: (Set<DayOfTheWeek>    -> unit)
    with
        member this.IsSelected (candidate: DayOfTheWeek) : bool =
            match this with
            | MaybeOne (Some day, _) -> day = candidate
            | One      (Some day, _) -> day = candidate
            | Set      (days,     _) -> days.Contains candidate
            | _                      -> false

        member this.OnPress (day: DayOfTheWeek) (_e: ReactEvent.Action) : unit =
            match this with
            | MaybeOne (Some selectedDay, onChange) when selectedDay = day -> onChange None
            | MaybeOne (_, onChange)                                       -> onChange (Some day)
            | One      (Some selectedDay, _onChange) when selectedDay = day -> Noop
            | One      (_, onChange)                                        -> onChange day
            | Set      (days, onChange)                                     -> onChange (days.Toggle day)

    let days = [
        DayOfTheWeek.Sunday
        DayOfTheWeek.Monday
        DayOfTheWeek.Tuesday
        DayOfTheWeek.Wednesday
        DayOfTheWeek.Thursday
        DayOfTheWeek.Friday
        DayOfTheWeek.Saturday
    ]


// Component extension lives in the LibClient.Components namespace.
namespace LibClient.Components

open Fable.React
open LibClient
open LibClient.Accessibility
open ReactXP.Components
open ReactXP.Styles

// NOTE: do NOT `open ReactXP.LegacyStyles` here. Its rule functions shadow the new-dialect ones
// and break make*Styles computation expressions. See the gallery docs runbooks/troubleshooting.md.

open LibClient.Components.Input.DayOfTheWeek

[<AutoOpen>]
module Input_DayOfTheWeek =

    module LC =
        module Input =
            module DayOfTheWeek =
                type Theme = {
                    UnselectedTextColor:       Color
                    UnselectedBackgroundColor: Color
                    SelectedTextColor:         Color
                    SelectedBackgroundColor:   Color
                    LabelColor:                Color
                    InvalidColor:              Color
                }

    open LC.Input.DayOfTheWeek

    [<RequireQualifiedAccess>]
    module private Styles =
        let private size = 38
        let private gap  = 10

        let days =
            makeViewStyles {
                FlexDirection.Row
                Overflow.Visible
                marginBottom 10
            }

        let label =
            makeViewStyles {
                marginBottom 15
            }

        let day =
            makeViewStyles {
                AlignItems.Center
                JustifyContent.Center
                Overflow.VisibleForTapCapture
                width        size
                height       size
                marginRight  gap
                borderRadius (size / 2)
            }

        let daySelected =
            ViewStyles.Memoize (fun (selectedBackgroundColor: Color) ->
                makeViewStyles {
                    backgroundColor selectedBackgroundColor
                }
            )

        let dayUnselected =
            ViewStyles.Memoize (fun (unselectedBackgroundColor: Color) ->
                makeViewStyles {
                    backgroundColor unselectedBackgroundColor
                }
            )

        let dayLabel =
            makeTextStyles {
                FontWeight.Bold
                fontSize 16
            }

        let dayLabelSelected =
            TextStyles.Memoize (fun (selectedTextColor: Color) ->
                makeTextStyles {
                    color selectedTextColor
                }
            )

        let dayLabelUnselected =
            TextStyles.Memoize (fun (unselectedTextColor: Color) ->
                makeTextStyles {
                    color unselectedTextColor
                }
            )

        let labelText =
            TextStyles.Memoize (fun (labelColor: Color) ->
                makeTextStyles {
                    color labelColor
                }
            )

        let labelTextInvalid =
            TextStyles.Memoize (fun (invalidColor: Color) ->
                makeTextStyles {
                    color invalidColor
                }
            )

        let invalidReasonText =
            TextStyles.Memoize (fun (invalidColor: Color) ->
                makeTextStyles {
                    fontSize 12
                    color invalidColor
                }
            )

    type LibClient.Components.Constructors.LC.Input with
        [<Component>]
        static member DayOfTheWeek(
                mode:           LibClient.Components.Input.DayOfTheWeek.Mode,
                validity:       InputValidity,
                ?label:         string,
                ?xLegacyStyles: List<ReactXP.LegacyStyles.RuntimeStyles>,
                ?key:           string
            ) : ReactElement =
            key |> ignore
            xLegacyStyles |> ignore

            let theTheme = Themes.GetMaybeUpdatedWith (None : Option<Theme -> Theme>)

            RX.View(
                children =
                    [|
                        // Label row: show label text if provided, or "Required" if Missing + no label
                        match label with
                        | Some lbl ->
                            RX.View(
                                styles   = [| Styles.label |],
                                children =
                                    [|
                                        LC.Text(
                                            lbl,
                                            styles =
                                                [|
                                                    if validity.IsInvalid then Styles.labelTextInvalid theTheme.InvalidColor
                                                    else                       Styles.labelText theTheme.LabelColor
                                                |]
                                        )
                                    |]
                            )
                        | None ->
                            if validity = Missing then
                                RX.View(
                                    styles   = [| Styles.label |],
                                    children =
                                        [|
                                            LC.Text(
                                                "Required",
                                                styles = [| Styles.labelTextInvalid theTheme.InvalidColor |]
                                            )
                                        |]
                                )
                            else
                                noElement

                        // Horizontal scroll of day buttons
                        RX.ScrollView(
                            horizontal = true,
                            children =
                                [|
                                    RX.View(
                                        styles   = [| Styles.days |],
                                        children =
                                            [|
                                                for day in LibClient.Components.Input.DayOfTheWeek.days do
                                                    let isSelected = mode.IsSelected day
                                                    let dayLabel = day.ToString()
                                                    RX.View(
                                                        styles =
                                                            [|
                                                                Styles.day
                                                                if isSelected then Styles.daySelected theTheme.SelectedBackgroundColor
                                                                else               Styles.dayUnselected theTheme.UnselectedBackgroundColor
                                                            |],
                                                        children =
                                                            [|
                                                                LC.Text(
                                                                    day.ToString().Substring(0, 3),
                                                                    styles =
                                                                        [|
                                                                            Styles.dayLabel
                                                                            if isSelected then Styles.dayLabelSelected theTheme.SelectedTextColor
                                                                            else               Styles.dayLabelUnselected theTheme.UnselectedTextColor
                                                                        |]
                                                                )
                                                                LC.Pressable(
                                                                    onPress = mode.OnPress day,
                                                                    label = dayLabel,
                                                                    testId = A11ySlug.testId "day-of-week" dayLabel,
                                                                    role = AccessibilityRole.Button,
                                                                    state = { AccessibilityStateRecord.empty with Selected = Some isSelected },
                                                                    overlay = true,
                                                                    componentName = "LC.Input.DayOfTheWeek"
                                                                )
                                                            |]
                                                    )
                                            |]
                                    )
                                |]
                        )

                        // Invalid reason below the days
                        match validity.InvalidReason with
                        | Some reason ->
                            RX.View(
                                children =
                                    [|
                                        LC.Text(reason, styles = [| Styles.invalidReasonText theTheme.InvalidColor |])
                                    |]
                            )
                        | None -> noElement
                    |]
            )
