[<AutoOpen>]
module LibClient.Components.ImageCard

open Fable.React
open LibClient
open LibClient.Accessibility
open ReactXP.Components
open ReactXP.Styles
// NOTE: do NOT `open ReactXP.LegacyStyles` here. Its rule functions shadow the new-dialect ones
// and break make*Styles CEs. The compat shim below uses a separate module block.

// Public types are kept at the canonical module path `LibClient.Components.ImageCard.*` because
// autogenerated callers (and Suite apps) reference them as fully-qualified names such as
// `LibClient.Components.ImageCard.Text ("...", LibClient.Components.ImageCard.UseScrim.No)`.

[<RequireQualifiedAccess>]
type UseScrim =
| Yes
| No

type Label =
| Text     of string * UseScrim
| Children of UseScrim
with
    member this.UseScrim : bool =
        match this with
        | Text     (_, UseScrim.Yes) -> true
        | Children     UseScrim.Yes  -> true
        | _                          -> false

type Style =
| Flat
| Shadowed

type Corners =
| Sharp
| Rounded

// Convenience alias kept for callers that used the old module-level binding.
let ofUrl = LibClient.Services.ImageService.ImageSource.ofUrl

[<RequireQualifiedAccess>]
module private Styles =
    // The `view` block carries FlexDirection + JustifyContent unconditionally;
    // per-Corners and per-Style variants are applied as separate style objects.
    let view =
        makeViewStyles {
            Position.Relative
            FlexDirection.Column
            JustifyContent.FlexEnd
        }

    let viewRounded =
        makeViewStyles { borderRadius 6 }

    let viewShadowed =
        makeViewStyles { shadow (Color.BlackAlpha 0.3) 4 (0, 1) }

    let image =
        makeViewStyles {
            Position.Absolute
            trbl 0 0 0 0
        }

    let scrim =
        makeViewStyles {
            Position.Absolute
            trbl            0 0 0 0
            backgroundColor (Color.BlackAlpha 0.4)
        }

    let labelTextWrapper =
        makeViewStyles { paddingHV 16 8 }

type LibClient.Components.Constructors.LC with
    [<Component>]
    static member ImageCard(
            source:         LibClient.Services.ImageService.ImageSource,
            ?label:         Label,
            ?style:         Style,
            ?corners:       Corners,
            ?onPress:       ReactEvent.Action -> unit,
            ?testId:        string,
            ?styles:        array<ViewStyles>,
            ?labelStyles:   array<TextStyles>,
            ?children:      array<ReactElement>,
            ?xLegacyStyles: List<ReactXP.LegacyStyles.RuntimeStyles>,
            ?key:           string
        ) : ReactElement =
        ignore key
        let children    = defaultArg children  [||]
        let style       = defaultArg style     Style.Flat
        let corners     = defaultArg corners   Corners.Sharp
        let extraStyles = defaultArg styles    [||]

        // Bridge xLegacyStyles from render-DSL callers into the root view styles.
        let legacyViewStyles : array<ViewStyles> =
            match xLegacyStyles with
            | Some ls ->
                match ReactXP.LegacyStyles.Runtime.findTopLevelBlockStyles ls with
                | []   -> [||]
                | stls -> [| ReactXP.LegacyStyles.Runtime.prepareStylesForPassingToReactXpComponent<ViewStyles> "ReactXP.Components.View" stls |]
            | None -> [||]

        LC.With.Layout(
            initialOnly = true,
            ``with`` =
                fun (onLayoutOption, maybeLayout) ->
                    RX.View(
                        ?onLayout = onLayoutOption,
                        styles =
                            [|
                                Styles.view
                                if corners = Corners.Rounded then Styles.viewRounded
                                if style   = Style.Shadowed  then Styles.viewShadowed
                                yield! extraStyles
                                yield! legacyViewStyles
                            |],
                        children =
                            [|
                                // Background image fills the view.
                                RX.Image(
                                    styles     = [| Styles.image |],
                                    source     = source,
                                    resizeMode = ReactXP.Components.Image.ResizeMode.Cover,
                                    size       = ReactXP.Components.Image.Size.FromParentLayout maybeLayout
                                )

                                // Optional label block (scrim + text or custom children).
                                match label with
                                | None -> ()
                                | Some lbl ->
                                    RX.View(
                                        children =
                                            [|
                                                if lbl.UseScrim then
                                                    RX.View(styles = [| Styles.scrim |])

                                                match lbl with
                                                | Label.Text (text, _) ->
                                                    RX.View(
                                                        styles   = [| Styles.labelTextWrapper |],
                                                        children =
                                                            [|
                                                                LC.UiText(text, ?styles = labelStyles)
                                                            |]
                                                    )
                                                | Label.Children _ ->
                                                    castAsElement children
                                            |]
                                    )

                                // Tap handler rendered as a sibling overlay when onPress is provided.
                                match onPress with
                                | Some f ->
                                    let a11yLabel =
                                        match label with
                                        | Some (Label.Text (text, _)) -> text
                                        | Some (Label.Children _) -> "Image"
                                        | None -> "Open image"
                                    let resolvedTestId =
                                        testId |> Option.orElse (Some (A11ySlug.testId "image-card" a11yLabel))
                                    LC.Pressable(
                                        onPress = f,
                                        label = a11yLabel,
                                        testId = resolvedTestId.Value,
                                        role = AccessibilityRole.Button,
                                        overlay = true,
                                        componentName = "LC.ImageCard"
                                    )
                                | None -> ()
                            |]
                    )
        )

// ---------------------------------------------------------------------------
// Backward-compatibility shim for Suite apps that reference `ImageCardStyles`.
// `ImageCardStyles.Theme.One` produces a legacy `Styles` value used as
// `xLegacyStyles` on `LC.ImageCard` calls.  Do NOT remove until all Suite
// callers are migrated to the modern `?styles` / `?labelStyles` API.
// ---------------------------------------------------------------------------
module ImageCardStyles =
    open ReactXP.LegacyStyles

    let private baseStyles = lazy (asBlocks [
        "image" => [
            Position.Absolute
            trbl 0 0 0 0
        ]

        "view" => [
            FlexDirection.Column
            JustifyContent.FlexEnd
        ] && [
            $"corners-{Corners.Rounded}" => [
                borderRadius 6
            ]

            $"style-{Style.Shadowed}" => [
                shadow (Color.BlackAlpha 0.3) 4 (0, 1)
            ]
        ]

        "scrim" => [
            Position.Absolute
            trbl            0 0 0 0
            backgroundColor (Color.BlackAlpha 0.4)
        ]

        "label-text-wrapper" => [
            paddingHV 16 8
        ]
    ])

    type (* class to enable named parameters *) Theme() =
        static let customize = makeCustomize("LibClient.Components.ImageCard", baseStyles)

        static member All (theHeight: int, textColor: Color, ?theFontSize: int) : unit =
            customize [
                Theme.Rules (theHeight, textColor, ?theFontSize = theFontSize)
            ]

        static member One (theHeight: int, textColor: Color, ?theFontSize: int) : Styles =
            Theme.Rules (theHeight, textColor, ?theFontSize = theFontSize) |> makeSheet

        static member Rules (theHeight: int, textColor: Color, ?theFontSize: int) : List<ISheetBuildingBlock> =
            let theFontSize = defaultArg theFontSize 16
            [
                "view" => [
                    height theHeight
                ]

                "label-text" => [
                    color    textColor
                    fontSize theFontSize
                ]
            ]

    let styles = lazy (compile (List.concat [
        baseStyles.Value
        Theme.Rules (
            theHeight = 200,
            textColor = Color.White
        )
    ]))
