#!/usr/bin/env bash
# Path guard for CLAUDE.md rules 7/8.
# usage: forbidden-path-guard.sh [--staged | file...]
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

paths=()
if [[ "${1:-}" == "--staged" ]]; then
    while IFS= read -r line; do paths+=("$line"); done < <(git diff --cached --name-only --diff-filter=ACMR)
else
    if [[ $# -gt 0 ]]; then
        paths=("$@")
    elif [[ ! -t 0 ]]; then
        while IFS= read -r line; do paths+=("$line"); done
    fi
fi

err=0
warn=0
for ((i = 0; i < ${#paths[@]}; i++)); do
    p="${paths[i]}"
    [[ -n "$p" ]] || continue

    if [[ "$p" == *.render ]]; then
        echo "FAIL: $p - CLAUDE.md rule 7: never edit .render files; convert to pure F#" >&2
        err=1
        continue
    fi

    if [[ "$p" == *_autogenerated_* ]]; then
        echo "FAIL: $p - CLAUDE.md rule 7: never hand-edit _autogenerated_; regenerate from .render then convert" >&2
        err=1
        continue
    fi

    if [[ "$p" == *.typext.fs ]]; then
        echo "FAIL: $p - CLAUDE.md rule 7: .typext.fs is part of the retired render DSL; convert to pure F#" >&2
        err=1
        continue
    fi

    if [[ "$p" == *.fs.js && ! ("$p" == .build/* || "$p" == */.build/*) ]]; then
        echo "FAIL: $p - CLAUDE.md: generated .fs.js belongs under .build/<platform>/ and is git-ignored; do not commit it" >&2
        err=1
        continue
    fi

    if [[ "$p" =~ (^|/)App[^/]+/ ]] || [[ "$p" =~ (^|/)Suite[^/]+/ ]]; then
        echo "WARNING: $p - CLAUDE.md rule 8: App*/Suite* paths need explicit user request; framework-only changes should live in Lib*" >&2
        warn=1
    fi
done

[[ $err -eq 0 ]] || exit 1

if [[ ${#paths[@]} -eq 0 ]]; then
    echo "OK: no paths to check"
else
    echo "OK: no forbidden paths"
fi
