#!/usr/bin/env bash
# run-scanner.sh -- run a per-file scanner over tracked, editable .fs files.
#
# The agentos custom-checks YAML cannot safely embed a double-quoted glob
# ("*.fs") inside a sh -c command: the vendored yaml_min loader over-
# escapes \" to \", so git ls-files sees the literal string \"*.fs\" and
# matches nothing, producing a silent false green. Delegating the file
# enumeration here keeps all quoting in plain bash where it is correct.
#
# Also excludes _autogenerated_/ and /.build/ paths: those are never-edit
# per path-policy.yaml (generated output) and eggshell-fmt does not
# auto-skip them despite its ignore-file comment, so flagging them is
# noise the agent cannot act on.
#
# usage: run-scanner.sh <scanner-cmd> [scanner-args...]
#   scanner-cmd   the tool to run, e.g. "dotnet tool run eggshell-fmt --"
#                 or "node .claude/skills/a11y-check/scripts/scan-a11y.mjs"
#   scanner-args  extra args passed after the file list (e.g. "--check")
# Exit codes:
#   0  scanner reported clean
#   1  scanner reported violations (propagated from the scanner)
#   2  the scanner tool is not installed / script missing (fail-open)
set -uo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $# -lt 1 ]]; then
    echo "usage: ${0##*/} <scanner-cmd> [scanner-args...]" >&2
    exit 2
fi

scanner=("$@")
files=()
while IFS= read -r f; do
    [[ "$f" == *_autogenerated_/* ]] && continue
    [[ "$f" == */.build/* ]] && continue
    files+=("$f")
done < <(git ls-files "*.fs" 2>/dev/null)

if [[ ${#files[@]} -eq 0 ]]; then
    echo "OK: no tracked .fs files to scan"
    exit 0
fi

# Run the scanner; capture its exit code (do not let set -e eat it).
set +e
"${scanner[@]}" "${files[@]}"
rc=$?
set -e
exit "$rc"
