#!/usr/bin/env bash
set -euo pipefail

# status-dashboard.sh — print markdown status snapshot to STDOUT
# Usage: scripts/status-dashboard.sh

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Counts. Legacy DSL artifacts only count inside framework source dirs (rule 8 scope);
# Meta/AppRenderDslCompiler test fixtures are intentional and excluded.
FRAMEWORK_SRC_DIRS=("$REPO_ROOT/LibClient/src" "$REPO_ROOT/LibUiComponents/src" "$REPO_ROOT/LibRouter/src" "$REPO_ROOT/LibAutoUi/src" "$REPO_ROOT/LibLifeCycleUi/src")
EXISTING_SRC_DIRS=()
for d in "${FRAMEWORK_SRC_DIRS[@]}"; do [ -d "$d" ] && EXISTING_SRC_DIRS+=("$d"); done
if [ ${#EXISTING_SRC_DIRS[@]} -eq 0 ]; then EXISTING_SRC_DIRS+=("$REPO_ROOT/LibClient"); fi

RENDER_COUNT=$(find "${EXISTING_SRC_DIRS[@]}" -name '*.render' 2>/dev/null | wc -l | tr -d ' ')
TYPEXT_COUNT=$(find "${EXISTING_SRC_DIRS[@]}" -name '*.typext.fs' 2>/dev/null | wc -l | tr -d ' ')
AUTOGEN_COUNT=$(find "${EXISTING_SRC_DIRS[@]}" -type d -name '_autogenerated_' 2>/dev/null | wc -l | tr -d ' ')
# Stray .fs.js = Fable output beside sources. .build/, node_modules/, fable_modules/ are legit locations.
STRAY_FSJS_COUNT=$(find "$REPO_ROOT" -name '*.fs.js' \
    -not -path '*/.build/*' -not -path '*/node_modules/*' -not -path '*/.git/*' -not -path '*/fable_modules/*' \
    | wc -l | tr -d ' ')
COMPONENT_COUNT=$(rg -l --fixed-strings '[<Component>]' "${EXISTING_SRC_DIRS[@]}" 2>/dev/null | wc -l | tr -d ' ')
GALLERY_PAGES_COUNT=$(find "$REPO_ROOT/AppEggShellGallery/src/Components/Content" -name '*.fs' | wc -l | tr -d ' ')
SKILL_COUNT=$(find "$REPO_ROOT/.claude/skills" -name 'SKILL.md' | wc -l | tr -d ' ')
AUDIT_SCRIPT_COUNT=$(find "$REPO_ROOT/AppEggShellGallery" -name 'audit-*.mjs' | wc -l | tr -d ' ')

# Git info
BRANCH=$(git -C "$REPO_ROOT" branch --show-current)
LAST_COMMIT_DATE=$(git -C "$REPO_ROOT" log -1 --format=%cd --date=short)

# Output
cat <<EOF
| Metric | Count |
|---|---|
| Legacy ".render" files | $RENDER_COUNT |
| Legacy ".typext.fs" files | $TYPEXT_COUNT |
| Legacy "_autogenerated_" dirs | $AUTOGEN_COUNT |
| Stray ".fs.js" files | $STRAY_FSJS_COUNT |
| LibClient [<Component>] components | $COMPONENT_COUNT |
| Gallery content pages | $GALLERY_PAGES_COUNT |
| Project skills | $SKILL_COUNT |
| Audit scripts | $AUDIT_SCRIPT_COUNT |
| Git branch | $BRANCH |
| Last commit date | $LAST_COMMIT_DATE |

generated: $(date +%Y-%m-%d)
EOF