#if !FAKE_BUILD_FSPROJ
#load "../../Fake/Includes.fsx"
#load "../../build-AllLibraries.fsx"
#load "../../Meta/AppRenderDslCompiler/build-AppRenderDslCompiler.fsx"
#load "../../Meta/AppEggshellCli/build-AppEggshellCli.fsx"
#load "../../LibClient/build-LibClient.fsx"
#load "../../LibRouter/build-LibRouter.fsx"
#load "../../LibUiSubject/build-LibUiSubject.fsx"
#endif

namespace Egg.Shell.AppTodo

module Build =
    open Fake.IO
    open Fake.DotNet
    open Fake.Core
    open Egg.Shell.Fake

    type Target =
    | InitializeDependencies
    | Clean
    | RestoreApp
    | EggShellPackageForWeb
    | InstallPackageDependencies
    | Eggshell of Command: string
    | RunServer of BackendUrl: string * AppUrlBase: string * Port: string

    let targetFactory =
        BuildFile.forPath __SOURCE_DIRECTORY__ __SOURCE_FILE__
        |> BuildFile.withTargetsFromUnionType
        |> BuildFile.withDefinition (fun buildContext normalizeDir ->
            function
            | InitializeDependencies ->
                NodeNpm.install buildContext

                [
                    ("./fsharplint.json", "../../Meta/fsharplint.json")
                    ("./public-dev/configSourceOverrides.dev.js", "../../configSourceOverrides.dev.js")
                ]
                |> List.map (fun (relativePath, relativeTargetPath) -> (normalizeDir relativePath, normalizeDir relativeTargetPath))
                |> List.iter (fun (path, targetPath) ->
                    if not (File.exists path) then
                        FileSystemHelper.CreateSymbolicLink path targetPath)

            | Clean ->
                Shell.rm_rf (normalizeDir "./node_modules")
                Shell.rm_rf (normalizeDir "./src/_autogenerated_")
                Shell.rm_rf (normalizeDir "./src/obj")
                Shell.rm_rf (normalizeDir "./src/bin")
                Shell.rm_rf (normalizeDir Constants.webPackagePath)

            | RestoreApp ->
                DotNetEx.restore (fun restoreOptions ->
                    { restoreOptions with
                        Common =
                            { restoreOptions.Common with
                                Verbosity = Some DotNet.Verbosity.Quiet }
                        Runtime = Some currentDotNetRuntimeIdentifier
                     }) (normalizeDir ".")

            | EggShellPackageForWeb ->
                EggShellCli.packageWeb buildContext

            | InstallPackageDependencies ->
                let buildContext = {
                    buildContext with
                        NormalizePath =
                            fun path ->
                                normalizeDir $"{Constants.webPackagePath}/{path}"
                }
                NodeNpm.install buildContext

            | RunServer (backendUrl, appUrlBase, port) ->
                CreateProcess.fromRawCommandLine "node" "server.js"
                |> CreateProcess.withWorkingDirectory (buildContext.NormalizePath Constants.webPackagePath)
                |> CreateProcess.setEnvironmentVariable "EGGSHELL_HttpPort" port
                |> CreateProcess.setEnvironmentVariable "EGGSHELL_AppUrlBase" appUrlBase
                |> CreateProcess.setEnvironmentVariable "EGGSHELL_BackendUrl" backendUrl
                |> CreateProcess.ensureExitCode
                |> Proc.run
                |> ignore

            | Eggshell command ->
                EggShellCli.execute buildContext command
            )
        |> BuildFile.withDefaultTarget InitializeDependencies
        |> BuildFile.withExternalDependency Egg.Shell.Meta.AppRenderDslCompiler.Build.targetFactory
            (Egg.Shell.Meta.AppRenderDslCompiler.Build.Target.Link >=> InitializeDependencies)
        |> BuildFile.withExternalDependency Egg.Shell.Meta.AppEggshellCli.Build.targetFactory
            (Egg.Shell.Meta.AppEggshellCli.Build.Build >=> EggShellPackageForWeb)
        |> BuildFile.withInternalDependency (InitializeDependencies >=> EggShellPackageForWeb)
        |> BuildFile.withInternalDependency (RestoreApp >=> EggShellPackageForWeb)
        |> BuildFile.withExternalDependency Egg.Shell.Build.targetFactory
            (Egg.Shell.Build.InitializeDependenciesForAllLibraries >=> EggShellPackageForWeb)
        |> BuildFile.withExternalDependency Egg.Shell.Meta.AppEggshellCli.Build.targetFactory
            (Egg.Shell.Meta.AppEggshellCli.Build.Build >=> InitializeDependencies)
        |> BuildFile.withExternalDependency Egg.Shell.LibClient.Build.targetFactory
            (Egg.Shell.LibClient.Build.EggShellBuildLib >=> InitializeDependencies)
        |> BuildFile.withExternalDependency Egg.Shell.LibRouter.Build.targetFactory
            (Egg.Shell.LibRouter.Build.EggShellBuildLib >=> InitializeDependencies)
        |> BuildFile.withExternalDependency Egg.Shell.LibUiSubject.Build.targetFactory
            (Egg.Shell.LibUiSubject.Build.InitializeDependencies >=> InitializeDependencies)
        |> BuildFile.withInternalDependency (EggShellPackageForWeb >=> InstallPackageDependencies)
        |> BuildFile.withInternalDependencyBuilder (function | Eggshell _ -> Some InitializeDependencies | RunServer _ -> Some InstallPackageDependencies | _ -> None)
        |> BuildFile.initialize
