// AUTO-GENERATED DO NOT EDIT
module AppEggShellGallery.ComponentRegistration

let registerAllTheThings () : unit =
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Avatar" AppEggShellGallery.Components.Content.AvatarRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Button" AppEggShellGallery.Components.Content.ButtonRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Buttons" AppEggShellGallery.Components.Content.ButtonsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Carousel" AppEggShellGallery.Components.Content.CarouselRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ColorVariants" AppEggShellGallery.Components.Content.ColorVariantsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ContextMenu" AppEggShellGallery.Components.Content.ContextMenuRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Dialogs" AppEggShellGallery.Components.Content.DialogsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ErrorBoundary" AppEggShellGallery.Components.Content.ErrorBoundaryRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Icon" AppEggShellGallery.Components.Content.IconRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.IconButton" AppEggShellGallery.Components.Content.IconButtonRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Icons" AppEggShellGallery.Components.Content.IconsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.InfoMessage" AppEggShellGallery.Components.Content.InfoMessageRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Input.Date" AppEggShellGallery.Components.Content.Input.DateRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Input.EmailAddress" AppEggShellGallery.Components.Content.Input.EmailAddressRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Input.PhoneNumber" AppEggShellGallery.Components.Content.Input.PhoneNumberRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Input.Picker" AppEggShellGallery.Components.Content.Input.PickerRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Input.Quantity" AppEggShellGallery.Components.Content.Input.QuantityRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Input.Text" AppEggShellGallery.Components.Content.Input.TextRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ItemList" AppEggShellGallery.Components.Content.ItemListRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Pre" AppEggShellGallery.Components.Content.PreRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Scrim" AppEggShellGallery.Components.Content.ScrimRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Stars" AppEggShellGallery.Components.Content.StarsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Tag" AppEggShellGallery.Components.Content.TagRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.TextButton" AppEggShellGallery.Components.Content.TextButtonRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ThirdParty.Map" AppEggShellGallery.Components.Content.ThirdParty.MapRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ThirdParty.Recharts" AppEggShellGallery.Components.Content.ThirdParty.RechartsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ThirdParty.ToolWindowContent" AppEggShellGallery.Components.Content.ThirdParty.ToolWindowContentRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Thumb" AppEggShellGallery.Components.Content.ThumbRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Thumbs" AppEggShellGallery.Components.Content.ThumbsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.TimeSpan" AppEggShellGallery.Components.Content.TimeSpanRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.Timestamp" AppEggShellGallery.Components.Content.TimestampRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.ToggleButtons" AppEggShellGallery.Components.Content.ToggleButtonsRender.render
    LibClient.ComponentRegistry.RegisterRender "AppEggShellGallery.Components.Content.WithSortAndFilter" AppEggShellGallery.Components.Content.WithSortAndFilterRender.render

    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Avatar", AppEggShellGallery.Components.Content.AvatarStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Buttons", AppEggShellGallery.Components.Content.ButtonsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Carousel", AppEggShellGallery.Components.Content.CarouselStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ColorVariants", AppEggShellGallery.Components.Content.ColorVariantsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ContextMenu", AppEggShellGallery.Components.Content.ContextMenuStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Dialogs", AppEggShellGallery.Components.Content.DialogsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ErrorBoundary", AppEggShellGallery.Components.Content.ErrorBoundaryStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Icon", AppEggShellGallery.Components.Content.IconStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.IconButton", AppEggShellGallery.Components.Content.IconButtonStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Icons", AppEggShellGallery.Components.Content.IconsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.InfoMessage", AppEggShellGallery.Components.Content.InfoMessageStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Input.Date", AppEggShellGallery.Components.Content.Input.DateStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Input.EmailAddress", AppEggShellGallery.Components.Content.Input.EmailAddressStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Input.PhoneNumber", AppEggShellGallery.Components.Content.Input.PhoneNumberStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Input.Picker", AppEggShellGallery.Components.Content.Input.PickerStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Input.Quantity", AppEggShellGallery.Components.Content.Input.QuantityStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Input.Text", AppEggShellGallery.Components.Content.Input.TextStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ItemList", AppEggShellGallery.Components.Content.ItemListStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Pre", AppEggShellGallery.Components.Content.PreStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Scrim", AppEggShellGallery.Components.Content.ScrimStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Stars", AppEggShellGallery.Components.Content.StarsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Tag", AppEggShellGallery.Components.Content.TagStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.TextButton", AppEggShellGallery.Components.Content.TextButtonStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ThirdParty.Map", AppEggShellGallery.Components.Content.ThirdParty.MapStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ThirdParty.Recharts", AppEggShellGallery.Components.Content.ThirdParty.RechartsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ThirdParty.ToolWindowContent", AppEggShellGallery.Components.Content.ThirdParty.ToolWindowContentStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Thumb", AppEggShellGallery.Components.Content.ThumbStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.Thumbs", AppEggShellGallery.Components.Content.ThumbsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.TimeSpan", AppEggShellGallery.Components.Content.TimeSpanStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.ToggleButtons", AppEggShellGallery.Components.Content.ToggleButtonsStyles.styles)
    LibClient.ComponentRegistry.RegisterStyles ("AppEggShellGallery.Components.Content.WithSortAndFilter", AppEggShellGallery.Components.Content.WithSortAndFilterStyles.styles)
