module AppEggShellGallery.DocsContent

// Native access to the bundled docs. On web the docs are fetched over HTTP (there is a server
// serving public-dev/docs), so this module is a no-op there and the generated 672 KB bundle is
// not pulled into the web build. On native there is no server, so DocsContent.generated.js
// (map of "<relative/path.md>" -> raw markdown, produced by scripts/gen-docs-bundle.js) is
// inlined and looked up here, then rendered via MarkdownViewer.Code. See
// RenderHelpers.docMarkdownSource.

#if !EGGSHELL_PLATFORM_IS_WEB
open Fable.Core.JsInterop

// ${entryDir} resolves (at Fable compile time) to the app's src dir -- same token the
// autogenerated LocalImagesRegistration.fs uses for native assets.
let private bundle: obj = importDefault "${entryDir}/DocsContent.generated.js"
#endif

/// The raw markdown for a doc path relative to public-dev/docs (e.g. "modernization/index.md"),
/// or None when unbundled / on web.
let tryGet (relativePath: string) : string option =
#if EGGSHELL_PLATFORM_IS_WEB
    ignore relativePath
    None
#else
    let value: obj = bundle?(relativePath)
    if isNullOrUndefined value then None else Some(unbox<string> value)
#endif
