module AppEggShellGallery.LocalImages

// AUTOGENERATED FILE, DO NOT EDIT MANUALLY

open Fable.Core.JsInterop

open LibClient
open LibClient.Services.ImageService

let localImage (filename: string) : ImageSource =
    match filename with

    | "/images/avatar.png" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/avatar.png")
        #endif

    | "/images/avatar2.png" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/avatar2.png")
        #endif

    | "/images/image-not-found.png" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/image-not-found.png")
        #endif

    | "/images/logo-sketch.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/logo-sketch.jpg")
        #endif

    | "/images/tifa.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/tifa.jpg")
        #endif

    | "/images/wlop1.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/wlop1.jpg")
        #endif

    | "/images/wlop2.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/wlop2.jpg")
        #endif

    | "/images/wlop3.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/wlop3.jpg")
        #endif

    | "/images/wlop4.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/wlop4.jpg")
        #endif

    | "/images/yuumei1.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/yuumei1.jpg")
        #endif

    | "/images/yuumei2.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/yuumei2.jpg")
        #endif

    | "/images/yuumei3.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/yuumei3.jpg")
        #endif

    | "/images/yuumei4.jpg" ->
        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath filename
        #else
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/yuumei4.jpg")
        #endif
    | _ ->
            Log.Error (sprintf "Image '%s' not found, at least not by the eggshell glob pattern. Maybe restart eggshell to see if that fixes the problem?" filename)

        #if EGGSHELL_PLATFORM_IS_WEB
            ImageSource.restricted_ofWebRelativePath "/images/image-not-found.png"
        #else
            // TODO fix this when dealing with native relative images
            ImageSource.restricted_ofNativeImport (importDefault "${entryDir}/../.build/native/assets/public-dev/images/image-not-found.png")
        #endif