#!/usr/bin/env node
// Advisory a11y scanner for .fs UI code. See docs accessibility/recipes.md.
// usage: scan-a11y.mjs <file.fs|dir>
import { readFileSync, statSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const SKIP_DIRS = new Set(['node_modules', '.build', 'fable_modules', '_autogenerated_', '.git']);
const target = process.argv[2];
if (!target) { console.error('usage: scan-a11y.mjs <file.fs|dir>'); process.exit(2); }

function* fsFiles(p) {
  const st = statSync(p);
  if (st.isFile()) { if (p.endsWith('.fs')) yield p; return; }
  for (const e of readdirSync(p, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue;
    yield* fsFiles(join(p, e.name));
  }
}

// Capture the argument window of a call: from the opening paren, until parens balance
// or 40 lines pass (heuristic for F# named-arg call layout).
function argWindow(lines, startIdx) {
  let depth = 0, out = [], started = false;
  for (let i = startIdx; i < Math.min(lines.length, startIdx + 40); i++) {
    for (const ch of lines[i]) {
      if (ch === '(') { depth++; started = true; }
      if (ch === ')') depth--;
    }
    out.push(lines[i]);
    if (started && depth <= 0) break;
  }
  return out.join('\n');
}

let count = 0;
const report = (file, line, msg) => { count++; console.log(`${file}:${line} ${msg}`); };

for (const file of fsFiles(target)) {
  const lines = readFileSync(file, 'utf8').split('\n');
  lines.forEach((line, i) => {
    const n = i + 1;
    if (/\bPressable\s*\(/.test(line) && !/^\s*\/\//.test(line)) {
      const w = argWindow(lines, i);
      if (!/\blabel\s*=/.test(w)) report(file, n, 'Pressable without label= (screen reader gets nothing)');
      if (!/\btestId\s*=/.test(w)) report(file, n, 'Pressable without testId= (automation cannot target it)');
    }
    if (/\b(TextInput|Input\.Text)\s*\(/.test(line) && !/^\s*\/\//.test(line)) {
      const w = argWindow(lines, i);
      if (!/\b(label|accessibilityLabel)\s*=/.test(w)) report(file, n, 'text input without an associated label');
    }
    if (/\bIcon\s*\(/.test(line) && /onPress/.test(argWindow(lines, i)) && !/\blabel\s*=/.test(argWindow(lines, i)))
      report(file, n, 'pressable icon without label (icon-only controls need names)');
  });
}
console.log(count === 0 ? 'OK: no a11y candidates' : `${count} candidate(s); judge against accessibility/recipes.md`);
